version: '3'

services:
   alpine-sqs:
     image: roribio16/alpine-sqs:latest
     container_name: alpine-sqs
     ports:
       - "9324:9324"
       - "9325:9325"
     stdin_open: true
     tty: true

